openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
  description: API for managing contacts
servers:
  - url: http://localhost:3000
    description: Local server
  - url: https://your-render-url.onrender.com
    description: Production server
paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        '200':
          description: A list of contacts
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          description: Contact created
  /contacts/{id}:
    get:
      summary: Get a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single contact
    put:
      summary: Update a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: Contact updated
    delete:
      summary: Delete a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Contact deleted
components:
  schemas:
    Contact:
      type: object
      required:
        - firstName
        - lastName
        - email
        - favoriteColor
        - birthday
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        favoriteColor:
          type: string
        birthday:
          type: string
          format: date